INSERT INTO trax_type (type_code) VALUES ('Cash');
INSERT INTO trax_type (type_code) VALUES ('POS');
INSERT INTO trax_type (type_code) VALUES ('CRD');
INSERT INTO trax_type (type_code) VALUES ('CHK');
INSERT INTO trax_type (type_code) VALUES ('DEP');
INSERT INTO trax_type (type_code) VALUES ('EFT');
INSERT INTO trax_type (type_code) VALUES ('ATM');
INSERT INTO trax_type (type_code) VALUES ('ADJ');
INSERT INTO account_list (account_name) VALUES ('test');
INSERT INTO account_list (account_number) VALUES ('1234A');
INSERT INTO account_list (account_contact) VALUES ('John Doe');
